import { Navigation } from '@/components/navigation/navigation'
import './globals.css'
import { IBM_Plex_Sans_Condensed } from 'next/font/google'
import { Header } from '@/components/header/header'

const IBM = IBM_Plex_Sans_Condensed({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={IBM.className}>
        <div className="wrapper">
          <Navigation></Navigation>


          <div className="main-section-container">
            <Header></Header>

            <main>
              {children}
            </main>

          </div>

        </div>
      </body>
    </html>
  )
}
