import { Providers } from '@/components/providers/providers'
import { Roboto } from 'next/font/google'
import { ProviderStore } from './Redux/provider'


const IBM = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={IBM.className}>
        <Providers>
          <ProviderStore>
            <div className="wrapper">
              {children}
            </div>
          </ProviderStore>
        </Providers>
      </body>
    </html>
  )
}